### ISSUE TITLE
Remove wp-retina-2x

### ISSUE THREAD

**Issue by luukdv** [trendwerk/bedrock#4]
We should remove this dependency since retina works out of the box as of 4.4.

**Comment by gewoonderrik** [comment]
Seems to work just fine! I've had a look at the source code on one of our latest projects and I can confirm that it works.

Looks as though the WordPress functionality uses viewport based selection rather than device-pixel-ratio, which is wat we currently use to display retina images. This methods makes images adapt to both the device-width and pixel-ratio. 

The source looks like this:

`<img class="alignright size-medium wp-image-410" src="http://fezcat.io/app/uploads/2016/02/fez-360x202.png" alt="Screen Shot 2016-03-17 at 14.09.31" width="360" height="202" srcset="http://fezcat.io/app/uploads/2016/02/fez-360x202.png 360w, http://fezcat.io/app/uploads/2016/02/fez-840x472.png 840w" sizes="(max-width: 360px) 100vw, 360px">`

For further information I suggest you guys should read [this](http://alistapart.com/article/using-responsive-images-now#section2 article).

**Comment by gewoonderrik** [comment]
@haroldangenent Kind sir, would you please remove remove WP Retina 2x for me? :tophat:

**Comment by haroldangenent** [comment]
Reopening this for more research.

**Comment by luukdv** [comment]
Done some additional research. Like I expected, WP doesn't generate a retina size, but only implements the existing sizes as srcset. In a lot of mobile portrait cases this won't be a problem, since our `large` width is set to `840`. This means there's enough retina data. For small (`120` currently) and medium (`360` currently) sized images this is also not a problem.

When viewing a large image on a tablet or retina laptop for example though, there's no retina image available.

So... Do we want to support these large editor images as retina?

**Comment by haroldangenent** [comment]
I don't think WP Retina 2x is worth that feature for _every_ install.

**Comment by luukdv** [comment]
Agreed. @gewoonderrik @sboerrigter?

**Comment by haroldangenent** [comment]
Feel free to reopen.
